# Generated by Django 5.0.4 on 2024-05-02 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogger',
            options={},
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='body',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='blogger',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='blogger',
            name='last_name',
        ),
    ]
