# Generated by Django 5.0.4 on 2024-05-02 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogger_options_rename_body_blog_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='bio',
            field=models.TextField(default='', help_text='Enter the bio of the blogger', max_length=1000),
        ),
    ]
