# Generated by Django 5.0.4 on 2024-05-05 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='Comment the blog', max_length=2000)),
                ('date_time', models.DateTimeField()),
            ],
            options={
                'ordering': ['date_time'],
                'permissions': (('can_comment', 'Can Comment'),),
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='comment',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
