# Generated by Django 5.0.4 on 2024-05-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_blog_comment_comment_blog_comment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
